### ISSUE TITLE
[EPIC] Scheduler UI

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#265]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We have a very basic scheduler UI. This issue is for tracking the work we need to do to make it useful.

**Describe the solution you'd like**

- [x] https://github.com/apache/arrow-ballista/pull/241
- [x] https://github.com/apache/arrow-ballista/issues/276
- [x] https://github.com/apache/arrow-ballista/issues/275
- [x] View query stages in a job
- [x] Cancel job

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by onthebridgetonowhere** [comment]
Looks like the Cancel job was merged, so this issue/epic could be successfully closed.  :fireworks:

**Comment by Dandandan** [comment]
Looks like the cancelling the job is not enabled yet in the UI - so reopening

**Comment by onthebridgetonowhere** [comment]
Good catch, sorry about that!

**Comment by andygrove** [comment]
Looks like we really can close this now. Thanks @Dandandan  and @onthebridgetonowhere
